### PR TITLE
Fix error handling during login

### LINKED ISSUE #18: Error message is not correctly displayed in the 2FA login mask
Current master on ownCloud 10:

If we enter a wrong OTP value, the error message is always "An error occurred while verifying the token", even though ``verifyChallenge`` returns more specific error messages. This is because this check: https://github.com/NetKnights-GmbH/privacyidea-owncloud-app/blob/1c8c65ecbcbc57709fcfced75789e1fac4c3c5db/twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php#L305
always fails, as it should apparently be
```php
        if (class_exists('OCP\Authentication\TwoFactorAuth\TwoFactorException')) {
```
(see [here](http://de2.php.net/manual/de/function.class-exists.php#82086))

### PR DESCRIPTION
**Pull request by fredreichbier**
Fixes #18 

* According to the 2FA API for ownCloud >= 9.2, ``TwoFactorException`` should be thrown if 2FA fails, which displays an error message to the user. Our code didn't do that until now (see #18). dad9e65 fixes this. But the question is whether this is desired behavior. e.g. if privacyIDEA cannot resolve the user, it returns a HTTP 400, and the login form then shows ``Failed to authenticate. Wrong HTTP return code.``. Do we want the user to know that?
* By default, the HTTP client throws an exception if the return code is not 200. However, our code explicitly checks the HTTP status code, so there is no need to throw an exception. cc2da96 fixes this by [passing exceptions=false](http://docs.guzzlephp.org/en/5.3/clients.html#exceptions).

### CODE REVIEW

**Comment by cornelinux** [comment]
Actually it was me, who added the ``TwoFactorException`` to owncloud! ;-)
Since we needed this to display messages like "please enter your OTP", in case of a challenge response!
I am not sure, if this PR would break this!

File: twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php [hunk 1]
```diff
@@ -302,7 +303,7 @@ public function verifyChallenge(IUser $user, $challenge)
                 ["message", $e->getMessage()]);
             $error_message = $this->trans->t("Failed to authenticate.") . " " . $e->getMessage();
         }
-        if (class_exists('TwoFactorException')) {
+        if (class_exists('OCP\Authentication\TwoFactorAuth\TwoFactorException')) {
```
Comment (cornelinux) [inline twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:306]: This is obviously OK here.

File: twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php [hunk 2]
```diff
@@ -234,7 +234,8 @@ private function getClientOptions()
             // NOTE: Here, we check for `!== '0'` instead of `=== '1'` in order to verify certificates
             // by default just after app installation.
             'verify' => $checkssl !== '0',
-            'debug' => false];
+            'debug' => false,
+            'exceptions' => false];
```
Comment (cornelinux) [inline twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:238]: I think this worked earlier. Maybe guzzle was updated...

**Review by cornelinux — APPROVED** [review]
