### PR TITLE
Fixed trigger challenge

### LINKED ISSUE #54: Challenge Response sends two emails (or more)
In certain cases two or more challenges are created.
Not sure if this is connected to the notification app. It was reported that it was connected to the guest app. But we could not reproduce this.

Anyways, this seems to be mitigated, if the App could check, if there is already a valid challenge.
In certain cases (parts of) the 2FA page gets reloaded. Then a new challenge is created and a new email is sent.
The initial response from the privacyIDEA system also contains the information how log the challenge is valid. We should investigate, if it is possible to store this information and - as long as the challenge is valid - not create a new challenge / => not send a new email.

### PR DESCRIPTION
**Pull request by Mipronimo**
In #54 @cornelinux mentioned a bug with the trigger challenge.
The problem seems to be, that a new challenge is triggered after a
reload (even if a user enters a wrong otp value).
This is fixed now, because we save the transaction id in the session.

closes #54

### CODE REVIEW

File: twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php [hunk 1]
```diff
@@ -221,20 +223,27 @@ private function triggerChallenges($username)
...
+			if ($this->getAppValue('triggerchallenges', '') === '1') {
+				try {
+					$messages = $this->triggerChallenges($user->getUID());
+					$this->session->set("pi_message", $messages);
+				} catch (TriggerChallengesException $e) {
+					$messages = [$e->getMessage()];
+				}
+			}
+		} else {
+    		$messages = $this->session->get("pi_message");
```
Comment (cornelinux) [inline twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:240]: If I have a "normal" second factor like a smartphone app or yubikey, that is *no* challenge response token and I use no triggerchallenge, would we then set the message to an emtpy string here?

Comment (Mipronimo) [reply twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:240]: Yes, but it is not displayed. If we do not sent a message, only the default one will be shown.

Bildschirmfoto vom 2019-05-31 08-23-15
