### PR TITLE
Small fixes

### LINKED ISSUE #12: Warning in log: "Undefined variable: u2fSignRequest"
Upon authentication, the following warning can be found in the ownCloud log:

```
{"reqId":"COvRBApSjA3ZbmiBFdh7","level":3,"time":"2017-12-19T08:10:03+00:00","remoteAddr":"192.168.33.1","user":"7cf7f772-d30d-1036-8008-cd5127ce8b3b","app":"PHP","method":"GET","url":"\/owncloud\/index.php\/login\/challenge\/privacyidea?redirect_url=","message":"Undefined variable: u2fSignRequest at \/var\/www\/owncloud\/apps\/twofactor_privacyidea\/templates\/challenge.php#28"}
```

### PR DESCRIPTION
**Pull request by fredreichbier**
Closes #12

### CODE REVIEW

File: twofactor_privacyidea/templates/challenge.php [hunk 1]
```diff
@@ -3,6 +3,8 @@
     $u2fSignRequest = $_["u2fSignRequest"];
     script('twofactor_privacyidea', 'u2f-api');
     script('twofactor_privacyidea', 'u2f');
+} else {
+    $u2fSignRequest = false;
```
Comment (cornelinux) [inline twofactor_privacyidea/templates/challenge.php:7]: @fredreichbier  Don't we need this variable in the later course?

Comment (fredreichbier) [reply twofactor_privacyidea/templates/challenge.php:7]: There is a ``if ($u2fSignRequest)`` later on. If $u2fSignRequest is uninitialized, everything works fine, but the warning from #12 is emitted.

Comment (cornelinux) [reply twofactor_privacyidea/templates/challenge.php:7]: Hm, and if it is set to ``false`` it does not work fine?
I do not understand why to remove this.

**Review by cornelinux — APPROVED** [review]
