### PR TITLE
Fixed multi challenge

### LINKED ISSUE #47: OTP input does not appear
If trigger challenge is enabled and the user has an otp and u2f, the otp field does not appear.

### PR DESCRIPTION
**Pull request by Mipronimo**
The app did not work correctly, if you have an otp and u2f enabled.
The trigger challenge did only checked the values in the attributes.
Only the token type of the last added token was used.
This is fixed now, by checking the values of multi_challenge.

closes #47

### CODE REVIEW

File: twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php [hunk 1]
```diff
@@ -180,19 +180,18 @@ private function triggerChallenges($username)
...
-                        if (property_exists($attributes, "u2fSignRequest")) {
-                            $this->u2fSignRequest = $attributes->u2fSignRequest;
+
+                    if (property_exists($detail, "multi_challenge")) {
+                        $multi_challenge = $detail->multi_challenge;
+                        for ($i = 0; $i < count($multi_challenge); $i++) {
+                            if ($multi_challenge[$i]->type === "u2f") {
+                                $this->u2fSignRequest = $multi_challenge[$i]->attributes->u2fSignRequest;
+                            } else {
+                                $this->hideOTPField = false;
```
Comment (cornelinux) [inline twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:191]: The hideOTPField should be previously probably "true"?

Comment (Mipronimo) [reply twofactor_privacyidea/lib/Provider/TwoFactorPrivacyIDEAProvider.php:191]: Fixed in 02be8a8

**Review by cornelinux — APPROVED** [review]
